runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /assets
  static_dir: assets

- url: /style
  static_dir: style

- url: /script
  static_dir: script

- url: /favicon\.ico
  static_files: assets/favicon.ico
  upload: assets/favicon\.ico

- url: /logo.png
  static_files: assets/logo.png
  upload: assets/logo.png

- url: .*
  script: main.application

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
- name: ssl
  version: 2.7.11